<a href="https://colab.research.google.com/github/Alister44/DTA_2026_DE/blob/main/Unterrichtsaufgaben/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐍 NumPy für angehende Datenanalysten

**NumPy** (Numerical Python) ist die grundlegende Bibliothek für die Arbeit mit numerischen Daten in Python. Sie ermöglicht:
- Große Zahlenarrays effizient zu speichern
- Mathematische Operationen schnell auszuführen (10–100 Mal schneller als normale Listen)
- Daten für die Analyse in pandas, matplotlib, scikit-learn vorzubereiten

---
**So verwendest du dieses Notebook:**
- 📖 Lies die Theorie in den Textzellen
- ▶️ Führe die Codezellen aus (Shift+Enter)
- ✏️ Bearbeite die Aufgaben — sie sind gekennzeichnet als **🎯 Aufgabe**
- Tipps in den Zellen nach jeder Aufgabe — nur aufklappen, wenn du nicht weiterkommst

---



## Kapitel 0 — Installation und Import

NumPy ist in der Regel bereits in Anaconda / Google Colab enthalten. Falls nicht — installiere es:


In [1]:
# Entkommentieren und ausführen, falls NumPy noch nicht installiert ist:
# !pip install numpy

import numpy as np

print("NumPy-Version:", np.__version__)
print("Import erfolgreich! ✅")


NumPy-Version: 2.0.2
Import erfolgreich! ✅


---
## Kapitel 1 — NumPy-Arrays (ndarray)

### Was ist ein Array?

Ein NumPy-Array (`ndarray`) ist wie eine Python-Liste, aber:
- alle Elemente haben **denselben Typ** (nur Zahlen oder nur Strings)
- benötigt **weniger Speicher**
- Mathematik kann **sofort auf das ganze Array** angewendet werden

```
Python-Liste:  [1, 2, 3, 4, 5]      ← normal, langsam
NumPy-Array:   array([1, 2, 3, 4, 5]) ← schnell, für Mathematik
```

### Ein Array erstellen


In [2]:
# Aus einer Python-Liste
arr1d = np.array([10, 20, 30, 40, 50])
print("1D-Array:", arr1d)
print("Typ:", type(arr1d))
print("Typ der Elemente:", arr1d.dtype)


1D-Array: [10 20 30 40 50]
Typ: <class 'numpy.ndarray'>
Typ der Elemente: int64


In [3]:
# 2D-Array (Matrix) — Liste aus Listen
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("2D-Array:")
print(arr2d)
print("\nForm (Zeilen, Spalten):", arr2d.shape)
print("Anzahl der Dimensionen:", arr2d.ndim)
print("Gesamtzahl der Elemente:", arr2d.size)


2D-Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Form (Zeilen, Spalten): (3, 3)
Anzahl der Dimensionen: 2
Gesamtzahl der Elemente: 9


In [4]:
# Nützliche Funktionen zum Erstellen von Arrays

zeros = np.zeros((3, 4))          # Array aus Nullen der Größe 3×4
ones = np.ones((2, 5))            # Array aus Einsen der Größe 2×5
rng = np.arange(0, 20, 2)         # Zahlen von 0 bis 19 mit Schrittweite 2
linspace = np.linspace(0, 1, 5)   # 5 gleichmäßig verteilte Zahlen von 0 bis 1

print("Nullen 3×4:\n", zeros)
print("\nEinsen 2×5:\n", ones)
print("\nBereich mit Schrittweite 2:", rng)
print("\nGleichmäßige Verteilung:", linspace)


Nullen 3×4:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Einsen 2×5:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Bereich mit Schrittweite 2: [ 0  2  4  6  8 10 12 14 16 18]

Gleichmäßige Verteilung: [0.   0.25 0.5  0.75 1.  ]


### 🎯 Aufgabe 1.1

Erstelle ein Array mit den Noten eines Studenten: `[85, 92, 78, 95, 88]`.
Gib das Array, seine Form und den Typ der Elemente aus.


In [5]:
# Dein Code hier:
grades = np.array([85, 92, 78, 95, 88])
print("ID array: ", grades)
print("Shape: ", grades.shape)
print("type elems: ", grades.dtype)



ID array:  [85 92 78 95 88]
Shape:  (5,)
type elems:  int64


In [6]:
# 💡 Tipp (ausführen, um ihn zu sehen):
hint = """
grades = np.array([85, 92, 78, 95, 88])
print(grades)
print(grades.shape)
print(grades.dtype)
"""
print(hint)



grades = np.array([85, 92, 78, 95, 88])
print(grades)
print(grades.shape)
print(grades.dtype)



### 🎯 Aufgabe 1.2

Erstelle ein zweidimensionales Array der Größe **4×3**, gefüllt mit Einsen.
Gib danach aus: Wie viele Elemente hat das Array insgesamt?


In [7]:
# Dein Code hier:
ones_array = np.ones((4,3))
print(ones_array)
print(ones_array.size)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
12


In [8]:
# 💡 Tipp:
hint = """
m = np.ones((4, 3))
print(m)
print("Anzahl der Elemente:", m.size)  # 12
"""
print(hint)



m = np.ones((4, 3))
print(m)
print("Anzahl der Elemente:", m.size)  # 12



---
## Kapitel 2 — Indizierung und Slicing

### Wie greift man auf Array-Elemente zu?

Die Indizierung ähnelt Python-Listen, aber für 2D-Arrays wird `[Zeile, Spalte]` verwendet:

```
arr = [10, 20, 30, 40, 50]
       ↑                ↑
     [0]              [4] oder [-1]
```


In [9]:
arr = np.array([10, 20, 30, 40, 50])

print("Erstes Element:      ", arr[0])     # 10
print("Drittes Element:     ", arr[2])     # 30
print("Letztes Element:     ", arr[-1])    # 50
print("Vorletztes Element:  ", arr[-2])    # 40


Erstes Element:       10
Drittes Element:      30
Letztes Element:      50
Vorletztes Element:   40


In [10]:
# Slicing: arr[start:stop:step]
# stop ist NICHT eingeschlossen!

arr = np.array([10, 20, 30, 40, 50, 60, 70])

print("arr[1:4]    =", arr[1:4])    # [20 30 40]
print("arr[:3]     =", arr[:3])     # [10 20 30] — vom Anfang
print("arr[4:]     =", arr[4:])     # [50 60 70] — bis zum Ende
print("arr[::2]    =", arr[::2])    # [10 30 50 70] — jedes zweite
print("arr[::-1]   =", arr[::-1])   # [70 60 50 40 30 20 10] — umgekehrt


arr[1:4]    = [20 30 40]
arr[:3]     = [10 20 30]
arr[4:]     = [50 60 70]
arr[::2]    = [10 30 50 70]
arr[::-1]   = [70 60 50 40 30 20 10]


In [11]:
l = [1,4,5,6,4]
l[2:]

[5, 6, 4]

In [12]:
# Indizierung eines 2D-Arrays
matrix = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

print("Matrix:\n", matrix)
print("\nElement [0, 2] (Zeile 0, Spalte 2):", matrix[0, 2])  # 3
print("Ganze Zeile 1:       ", matrix[1, :])   # [5 6 7 8]
print("Ganze Spalte 2:      ", matrix[:, 2])   # [3 7 11]
print("Untermatrix [1:, 1:3]:\n", matrix[1:, 1:3])


Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element [0, 2] (Zeile 0, Spalte 2): 3
Ganze Zeile 1:        [5 6 7 8]
Ganze Spalte 2:       [ 3  7 11]
Untermatrix [1:, 1:3]:
 [[ 6  7]
 [10 11]]


### 🎯 Aufgabe 2.1

Wir haben Verkaufsdaten für eine Woche: `[120, 85, 200, 95, 310, 280, 150]`
- Gib die Verkäufe der Werktage aus (Mo–Fr, Indizes 0–4)
- Gib die Verkäufe am Wochenende aus (Sa–So, letzte 2 Elemente)
- Gib nur die ungeraden Tage aus (Di, Do, Sa — Indizes 1, 3, 5)


In [13]:
sales = np.array([120, 85, 200, 95, 310, 280, 150])

# Dein Code hier:
print(sales[:5]) # Verkäufe an Werktagen (Mo–Fr)
print(sales[-2:]) # Verkäufe am Wochenende (Sa–So)
print(sales[1::2]) # nur ungerade Tage (Di, Do, Sa — Indizes 1, 3, 5)


[120  85 200  95 310]
[280 150]
[ 85  95 280]


In [14]:
my_list = [1, 2, 3]
my_list.append(4)
my_list.append([5,6])
# my_list[(1, 3)]  # ERROR

In [15]:
# 💡 Tipp:
hint = """
print("Werktage:", sales[:5])
print("Wochenende:", sales[-2:])
print("Di, Do, Sa:", sales[1::2])  oder  sales[[1, 3, 5]]
"""
print(hint)



print("Werktage:", sales[:5])
print("Wochenende:", sales[-2:])
print("Di, Do, Sa:", sales[1::2])  oder  sales[[1, 3, 5]]



### 🎯 Aufgabe 2.2

Wir haben eine Temperaturtabelle: 3 Städte × 5 Tage.
- Gib alle Temperaturen der ersten Stadt aus (Zeile 0)
- Gib die Temperaturen aller Städte am dritten Tag aus (Spalte 2)
- Gib die Untermatrix für die Städte 1–2 und die Tage 2–4 aus


In [16]:
# Temperaturen: Zeilen = Städte (Kyjiw, Charkiw, Odessa), Spalten = Tage (Mo–Fr)
temps = np.array([
    [18, 20, 22, 19, 21],   # Kyjiw
    [17, 19, 23, 20, 22],   # Charkiw
    [22, 24, 26, 25, 23]    # Odessa
])

# Dein Code hier:
print("Alle Temperaturen der ersten Stadt (Zeile 0) \n", temps[0, :])
print("Temperaturen aller Städte am dritten Tag (Spalte 2) \n", temps[:, 2])
print("Untermatrix für die Städte 1–2 und die Tage 2–4 \n", temps[:2, 1:4])




Alle Temperaturen der ersten Stadt (Zeile 0) 
 [18 20 22 19 21]
Temperaturen aller Städte am dritten Tag (Spalte 2) 
 [22 23 26]
Untermatrix für die Städte 1–2 und die Tage 2–4 
 [[20 22 19]
 [19 23 20]]


In [17]:
# 💡 Tipp:
hint = """
print(temps[0, :])      # erste Stadt
print(temps[:, 2])      # dritter Tag
print(temps[1:, 2:5])   # Untermatrix
"""
print(hint)



print(temps[0, :])      # erste Stadt
print(temps[:, 2])      # dritter Tag
print(temps[1:, 2:5])   # Untermatrix



---
## Kapitel 3 — Mathematische Operationen

### Vektorisierung — die Magie von NumPy

In NumPy werden Operationen **auf alle Elemente gleichzeitig** angewendet — das nennt man **Vektorisierung**:

```python
# Normales Python — braucht eine Schleife:
result = [x * 2 for x in [1, 2, 3, 4, 5]]

# NumPy — ohne Schleife, und viel schneller:
result = np.array([1, 2, 3, 4, 5]) * 2
```


In [18]:
prices = np.array([100, 250, 80, 320, 150])  # Preise in UAH

# Arithmetik mit einem Skalar (einer Zahl)
print("Preise:", prices)
print("Mit MwSt. (×1.2):", prices * 1.2)
print("20% Rabatt:  ", prices * 0.8)
print("+ 50 UAH:    ", prices + 50)


Preise: [100 250  80 320 150]
Mit MwSt. (×1.2): [120. 300.  96. 384. 180.]
20% Rabatt:   [ 80. 200.  64. 256. 120.]
+ 50 UAH:     [150 300 130 370 200]


In [19]:
# Operationen zwischen zwei Arrays — elementweise
qty = np.array([3, 1, 5, 2, 4])     # Anzahl der verkauften Produkte

revenue = prices * qty               # Umsatz pro Produkt
print("Preise:      ", prices)
print("Menge:       ", qty)
print("Umsatz:      ", revenue)
print("Gesamt:      ", revenue.sum())


Preise:       [100 250  80 320 150]
Menge:        [3 1 5 2 4]
Umsatz:       [300 250 400 640 600]
Gesamt:       2190


In [20]:
# Mathematische Funktionen von NumPy
data = np.array([4, 9, 16, 25, 36, 49])

print("Quadratwurzel:     ", np.sqrt(data))
print("Logarithmus (ln):  ", np.log(data).round(2))
print("Potenz ^2:         ", np.power(data, 2))
print("Absolutwert:", np.abs(np.array([-3, 5, -1, 8])))


Quadratwurzel:      [2. 3. 4. 5. 6. 7.]
Logarithmus (ln):   [1.39 2.2  2.77 3.22 3.58 3.89]
Potenz ^2:          [  16   81  256  625 1296 2401]
Absolutwert: [3 5 1 8]


In [21]:
# Aggregatfunktionen — fassen das ganze Array zusammen
scores = np.array([72, 88, 65, 91, 78, 84, 69, 95])

print("Noten:", scores)
print("Summe:      ", scores.sum())
print("Mittelwert: ", scores.mean().round(2))
print("Min:        ", scores.min())
print("Max:        ", scores.max())
print("Std.-Abw.:  ", scores.std().round(2))
print("Median:     ", np.median(scores))


Noten: [72 88 65 91 78 84 69 95]
Summe:       642
Mittelwert:  80.25
Min:         65
Max:         95
Std.-Abw.:   10.24
Median:      81.0


In [22]:
# Aggregation entlang der Achsen für ein 2D-Array
sales_matrix = np.array([
    [100, 150, 200],   # Geschäft 1: Mo, Di, Mi
    [80,  120, 180],   # Geschäft 2
    [200, 90,  160],   # Geschäft 3
])

print("Verkaufsmatrix:\n", sales_matrix)
print("\nSumme pro Zeile (pro Geschäft):     ", sales_matrix.sum(axis=1))
print("Summe pro Spalte (pro Tag):         ", sales_matrix.sum(axis=0))
print("Mittelwert pro Geschäft:", sales_matrix.mean(axis=1).round(1))


Verkaufsmatrix:
 [[100 150 200]
 [ 80 120 180]
 [200  90 160]]

Summe pro Zeile (pro Geschäft):      [450 380 450]
Summe pro Spalte (pro Tag):          [380 360 540]
Mittelwert pro Geschäft: [150.  126.7 150. ]


### 🎯 Aufgabe 3.1

Es gibt Gehaltsdaten von 6 Mitarbeitern in Dollar: `[1200, 1500, 900, 2100, 1800, 1350]`

1. Rechne die Gehälter in UAH um (Kurs: 1 USD = 41 UAH)
2. Berechne das durchschnittliche, minimale und maximale Gehalt in UAH
3. Bestimme, um wie viel jedes Gehalt vom Durchschnitt abweicht


In [23]:
salaries_usd = np.array([1200, 1500, 900, 2100, 1800, 1350])

# Dein Code hier:
salaries_uah = salaries_usd * 41
print(salaries_uah)

print("Durchschnitt: ", salaries_uah.mean())
print("Minimum: ", salaries_uah.min())
print("Maximum: ", salaries_uah.max())

diff = salaries_uah - salaries_uah.mean()
print("Abweichung vom Durchschnitt:", diff.round())


[49200 61500 36900 86100 73800 55350]
Durchschnitt:  60475.0
Minimum:  36900
Maximum:  86100
Abweichung vom Durchschnitt: [-11275.   1025. -23575.  25625.  13325.  -5125.]


In [24]:
# 💡 Tipp:
hint = """
salaries_uah = salaries_usd * 41
print("In UAH:", salaries_uah)

print("Durchschnitt: ", salaries_uah.mean())
print("Minimum: ", salaries_uah.min())
print("Maximum: ", salaries_uah.max())

diff = salaries_uah - salaries_uah.mean()
print("Abweichung vom Durchschnitt:", diff.round())
"""
print(hint)



salaries_uah = salaries_usd * 41
print("In UAH:", salaries_uah)

print("Durchschnitt: ", salaries_uah.mean())
print("Minimum: ", salaries_uah.min())
print("Maximum: ", salaries_uah.max())

diff = salaries_uah - salaries_uah.mean()
print("Abweichung vom Durchschnitt:", diff.round())



### 🎯 Aufgabe 3.2

Wir haben eine Verkaufstabelle von 4 Managern über 3 Monate (Zeilen = Manager, Spalten = Monate):

1. Finde den Gesamtumsatz jedes Managers
2. Finde den besten Monat (Maximum pro Spalte)
3. Finde den besten Manager (Tipp: `np.argmax()`)


In [25]:
managers_sales = np.array([
    [45000, 52000, 48000],  # Manager 1
    [38000, 61000, 55000],  # Manager 2
    [72000, 68000, 70000],  # Manager 3
    [41000, 44000, 39000],  # Manager 4
])

# Dein Code hier:
total = managers_sales.sum(axis = 1)
print(f"Gesamtumsatz jedes Managers: {total}")
print(f"Bester Monat: {managers_sales.max(axis = 0)}")
best_manager = np.argmax(total)+1
print(f"Bester Manager № {best_manager}")


Gesamtumsatz jedes Managers: [145000 154000 210000 124000]
Bester Monat: [72000 68000 70000]
Bester Manager № 3


In [26]:
# 💡 Tipp:
hint = """
total = managers_sales.sum(axis=1)
print("Summen der Manager:", total)

best_month = managers_sales.max(axis=0)
print("Bester Monat:       ", best_month)

best_manager = np.argmax(total)   # gibt den Index zurück
print(f"Bester Manager: #{best_manager + 1} mit Summe {total[best_manager]}")
"""
print(hint)



total = managers_sales.sum(axis=1)
print("Summen der Manager:", total)

best_month = managers_sales.max(axis=0)
print("Bester Monat:       ", best_month)

best_manager = np.argmax(total)   # gibt den Index zurück
print(f"Bester Manager: #{best_manager + 1} mit Summe {total[best_manager]}")



---
## Kapitel 4 — Boolesche Indizierung und Filterung

### Wie filtert man Daten?

Das ist eine der wichtigsten Techniken für die Datenanalyse!
Statt `for`-Schleifen mit `if`-Bedingungen — ein einfacher Ausdruck:


In [27]:
ages = np.array([23, 45, 18, 67, 31, 29, 52, 19, 38, 41])

# Boolesche Maske — Array aus True/False
mask = ages > 30
print("Maske (Alter > 30):", mask)

# Anwendung der Maske — behält nur die True-Elemente
seniors = ages[mask]
print("Personen über 30:  ", seniors)

# Kurz — in einer Zeile:
print("Jünger als 25:     ", ages[ages < 25])


Maske (Alter > 30): [False  True False  True  True False  True False  True  True]
Personen über 30:   [45 67 31 52 38 41]
Jünger als 25:      [23 18 19]


& (und), and
| (oder), or
~ (nicht) not


In [28]:
# Komplexe Bedingungen: & (und), | (oder), ~ (nicht)
# WICHTIG: jede Bedingung in Klammern!

# Personen von 25 bis 45 Jahren
middle = ages[(ages >= 25) & (ages <= 45)]
print("Von 25 bis 45:", middle)

# Jünger als 20 oder älter als 60
extremes = ages[(ages < 20) | (ages > 60)]
print("< 20 oder > 60:", extremes)


Von 25 bis 45: [45 31 29 38 41]
< 20 oder > 60: [18 67 19]


In [29]:
# np.where — bedingte Zuweisung (wie IF in Excel)
scores = np.array([72, 88, 55, 91, 48, 78, 63, 95])

# np.where(Bedingung, Wert_wenn_True, Wert_wenn_False)
grades = np.where(scores >= 75, "✅ bestanden", "❌ nicht bestanden")
print("Noten:  ", scores)
print("Status: ", grades)


Noten:   [72 88 55 91 48 78 63 95]
Status:  ['❌ nicht bestanden' '✅ bestanden' '❌ nicht bestanden' '✅ bestanden'
 '❌ nicht bestanden' '✅ bestanden' '❌ nicht bestanden' '✅ bestanden']


In [30]:
# Nützliche Suchfunktionen
temps = np.array([22, 35, 18, 41, 29, 37, 15, 44])

print("Index des Minimums:", np.argmin(temps), "— Wert:", temps[np.argmin(temps)])
print("Index des Maximums:", np.argmax(temps), "— Wert:", temps[np.argmax(temps)])
print("Tage > 35°C:", np.sum(temps > 35), "Tage")
print("Prozent heiße Tage:", (np.sum(temps > 35) / len(temps) * 100), "%")


Index des Minimums: 6 — Wert: 15
Index des Maximums: 7 — Wert: 44
Tage > 35°C: 3 Tage
Prozent heiße Tage: 37.5 %


### 🎯 Aufgabe 4.1

Es gibt Aktienkursdaten für 10 Tage. Finde:
1. Tage, an denen der Kurs über dem Durchschnitt lag
2. Wie viele Tage ist der Kurs gefallen (unter 100)?
3. Markiere jeden Tag: "Anstieg" oder "Rückgang" relativ zu 100


In [31]:
stock_prices = np.array([95, 102, 98, 115, 88, 121, 94, 108, 87, 119])

# Dein Code hier:
print("Tage, an denen der Kurs über dem Durchschnitt lag",stock_prices[stock_prices > stock_prices.mean()])
print("Wie viele Tage ist der Kurs gefallen (unter 100)?",np.sum(stock_prices<100))
print("Markiere jeden Tag: 'Anstieg' oder 'Rückgang' relativ zu 100",np.where(stock_prices < 100,'Rückgang','Anstieg'))




Tage, an denen der Kurs über dem Durchschnitt lag [115 121 108 119]
Wie viele Tage ist der Kurs gefallen (unter 100)? 5
Markiere jeden Tag: 'Anstieg' oder 'Rückgang' relativ zu 100 ['Rückgang' 'Anstieg' 'Rückgang' 'Anstieg' 'Rückgang' 'Anstieg' 'Rückgang'
 'Anstieg' 'Rückgang' 'Anstieg']


In [32]:
# 💡 Tipp:
hint = """
avg = stock_prices.mean()
print("Preise über dem Durchschnitt:", stock_prices[stock_prices > avg])

print("Tage < 100:", np.sum(stock_prices < 100))

trend = np.where(stock_prices >= 100, "Anstieg", "Rückgang")
print("Trend:", trend)
"""
print(hint)



avg = stock_prices.mean()
print("Preise über dem Durchschnitt:", stock_prices[stock_prices > avg])

print("Tage < 100:", np.sum(stock_prices < 100))

trend = np.where(stock_prices >= 100, "Anstieg", "Rückgang")
print("Trend:", trend)



### 🎯 Aufgabe 4.2 — Komplex

Es gibt Daten von Kunden eines Online-Shops: Alter und Bestellsumme.

1. Finde die durchschnittliche Bestellung von Kunden unter 30 Jahren
2. Finde die Anzahl der Kunden von 30 bis 50 mit einer Bestellung > 500
3. Bestimme VIP-Kunden (Bestellung > 1000) und gib ihr Alter aus


In [33]:
client_age    = np.array([24, 45, 31, 19, 52, 28, 36, 41, 27, 58, 33, 22])
order_amount  = np.array([350, 820, 450, 120, 1200, 680, 950, 310, 780, 1500, 420, 290])

# Dein Code hier:
print('Durchschnittliche Bestellung von Kunden unter 30 Jahren', order_amount[client_age < 30].mean())
print('2. Anzahl der Kunden von 30 bis 50 mit einer Bestellung > 500',np.sum((client_age >= 30) & (client_age < 50) & (order_amount > 500)))
print('3. VIP-Kunden (Bestellung > 1000), ihr Alter', client_age[order_amount > 1000])



Durchschnittliche Bestellung von Kunden unter 30 Jahren 444.0
2. Anzahl der Kunden von 30 bis 50 mit einer Bestellung > 500 2
3. VIP-Kunden (Bestellung > 1000), ihr Alter [52 58]


In [34]:
# 💡 Tipp:
hint = """
young_orders = order_amount[client_age < 30]
print("Durchschnittliche Bestellung unter 30J:", young_orders.mean())

mask_mid = (client_age >= 30) & (client_age <= 50) & (order_amount > 500)
print("30-50 mit > 500 UAH:", np.sum(mask_mid))

vip_ages = client_age[order_amount > 1000]
print("VIP-Kunden, Alter:", vip_ages)
"""
print(hint)



young_orders = order_amount[client_age < 30]
print("Durchschnittliche Bestellung unter 30J:", young_orders.mean())

mask_mid = (client_age >= 30) & (client_age <= 50) & (order_amount > 500)
print("30-50 mit > 500 UAH:", np.sum(mask_mid))

vip_ages = client_age[order_amount > 1000]
print("VIP-Kunden, Alter:", vip_ages)



---
## Kapitel 5 — Form ändern und Sortieren

### reshape — die Form eines Arrays ändern


In [35]:
# Wir starten mit einem 1D-Array aus 12 Elementen
flat = np.arange(1, 13)
print("Eindimensional:", flat)

# Umwandlung in Matrizen — die Anzahl der Elemente muss übereinstimmen!
matrix_3x4 = flat.reshape(3, 4)   # 3 Zeilen × 4 Spalten = 12
matrix_4x3 = flat.reshape(4, 3)   # 4 Zeilen × 3 Spalten = 12
matrix_2x6 = flat.reshape(2, 6)   # 2 Zeilen × 6 Spalten = 12

print("\n3×4:\n", matrix_3x4)
print("\n4×3:\n", matrix_4x3)


Eindimensional: [ 1  2  3  4  5  6  7  8  9 10 11 12]

3×4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

4×3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
# -1 bedeutet "NumPy berechnet es selbst"
arr = np.arange(24) # erzeugt ein Array von 0-24
m = arr.reshape(4, -1)     # 4 Zeilen, Spalten — automatisch (6)
print("reshape(4, -1):\n", m)
print("Form:", m.shape)

# Zurück zu 1D
flat_again = m.flatten()
print("\nflatten:", flat_again)


reshape(4, -1):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Form: (4, 6)

flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [37]:
# Sortieren
data = np.array([64, 23, 87, 12, 45, 91, 38])

print("Original:            ", data)
print("Sortiert (↑):        ", np.sort(data))
print("Sortiert (↓):        ", np.sort(data)[::-1])
print("Sortier-Indizes:     ", np.argsort(data))  # Reihenfolge der Indizes


Original:             [64 23 87 12 45 91 38]
Sortiert (↑):         [12 23 38 45 64 87 91]
Sortiert (↓):         [91 87 64 45 38 23 12]
Sortier-Indizes:      [3 1 6 4 0 2 5]


### 🎯 Aufgabe 5.1

Wir haben ein 1D-Array mit 20 Testergebnissen. Wandle es in eine 4×5-Matrix um (4 Gruppen à 5 Studenten),
gib dann die Top-3-Ergebnisse der gesamten Stichprobe und den Durchschnitt jeder Gruppe aus.


In [38]:
test_results = np.array([72, 88, 55, 91, 48, 78, 63, 95, 69, 82,
                         74, 51, 87, 66, 93, 58, 79, 84, 61, 77])

# Dein Code hier:
new = test_results.reshape(4,5)
print(f"TOP 3: {np.sort(test_results)[-3:][::-1]}\n")

print(new)
group_avg = new.mean(axis=1).round(1)
print(f"Durchschnitt jeder Gruppe: ",group_avg)



TOP 3: [95 93 91]

[[72 88 55 91 48]
 [78 63 95 69 82]
 [74 51 87 66 93]
 [58 79 84 61 77]]
Durchschnitt jeder Gruppe:  [70.8 77.4 74.2 71.8]


In [39]:
# 💡 Tipp:
hint = """
groups = test_results.reshape(4, 5)
print("Matrix 4×5:\n", groups)

top3 = np.sort(test_results)[-3:]  # oder [::-1][:3]
print("Top-3:", top3)

group_avg = groups.mean(axis=1).round(1)
print("Durchschnitt pro Gruppe:", group_avg)
"""
print(hint)



groups = test_results.reshape(4, 5)
print("Matrix 4×5:
", groups)

top3 = np.sort(test_results)[-3:]  # oder [::-1][:3]
print("Top-3:", top3)

group_avg = groups.mean(axis=1).round(1)
print("Durchschnitt pro Gruppe:", group_avg)



---
## Kapitel 6 — Erzeugung von Zufallszahlen

Zufallszahlen werden benötigt für: Simulationen, Testdaten, maschinelles Lernen


In [40]:
# Seed-Einstellung — für reproduzierbare Ergebnisse
rng = np.random.default_rng(seed=42)   # moderne Methode

# Gleichverteilung — von 0 bis 1
uniform = rng.random(5)
print("Gleichverteilung [0,1):", uniform.round(3))

# Ganze Zahlen in einem Bereich
integers = rng.integers(1, 101, size=10)   # von 1 bis 100, 10 Stück
print("Ganze Zahlen von 1 bis 100:", integers)

# Normalverteilung (Mittelwert=0, σ=1)
normal = rng.normal(loc=170, scale=10, size=8)   # Körpergröße: μ=170, σ=10
print("Normalverteilung (Größe):", normal.round(1))


Gleichverteilung [0,1): [0.774 0.439 0.859 0.697 0.094]
Ganze Zahlen von 1 bis 100: [53 98 74 77 72 79 52 13 84 46]
Normalverteilung (Größe): [178.8 177.8 170.7 181.3 174.7 161.4 173.7 160.4]


In [41]:
# Mischen und Stichprobe
items = np.array(["Apfel", "Banane", "Birne", "Pfirsich", "Pflaume", "Mango"])

# Mischen
shuffled = rng.permutation(items)
print("Gemischt:", shuffled)

# 3 zufällige ohne Wiederholung auswählen
sample = rng.choice(items, size=3, replace=False)
print("Stichprobe 3:", sample)


Gemischt: ['Pfirsich' 'Birne' 'Banane' 'Mango' 'Pflaume' 'Apfel']
Stichprobe 3: ['Banane' 'Birne' 'Apfel']


### 🎯 Aufgabe 6.1

Simuliere 1000 Würfelwürfe. Berechne:
1. Wie oft jede Zahl von 1 bis 6 gefallen ist (Tipp: `np.bincount`)
2. Wie hoch ist die Häufigkeit der Sechs (in Prozent)?
3. Der Durchschnittswert über 1000 Würfe (theoretisch sollte er 3.5 sein)


In [42]:
rng = np.random.default_rng(seed=0)

# Dein Code hier:
rolls = rng.integers(1, 7, size = 1000)

# Wie oft jede Zahl von 1 bis 6 gefallen ist (Tipp: np.bincount)
n_count = np.bincount(rolls)[1:]
print('Wie oft jede Zahl von 1 bis 6 gefallen ist', n_count)
# Wie hoch ist die Häufigkeit der Sechs (in Prozent)?
print(n_count[5] / len(rolls) * 100)

# Durchschnittswert über 1000 Würfe (theoretisch sollte er 3.5 sein)
rolls.mean()


Wie oft jede Zahl von 1 bis 6 gefallen ist [151 164 148 182 181 174]
17.4


np.float64(3.6)

In [43]:
# 💡 Tipp:
hint = """
rolls = rng.integers(1, 7, size=1000)

counts = np.bincount(rolls)[1:]  # [1:] um den nullten Index zu entfernen
print("Anzahl jeder Zahl:", counts)

print("Häufigkeit der Sechs: ", round(np.sum(rolls == 6) / 1000 * 100, 1), "%")
print("Durchschnitt:         ", rolls.mean().round(3))
"""
print(hint)



rolls = rng.integers(1, 7, size=1000)

counts = np.bincount(rolls)[1:]  # [1:] um den nullten Index zu entfernen
print("Anzahl jeder Zahl:", counts)

print("Häufigkeit der Sechs: ", round(np.sum(rolls == 6) / 1000 * 100, 1), "%")
print("Durchschnitt:         ", rolls.mean().round(3))



---
## 🏆 Abschlussprojekt — Analyse der Shop-Daten

Nutze alles, was du gelernt hast! Wir haben Daten eines Online-Shops für einen Monat.


In [44]:
# Shop-Daten
np.random.seed(42)

n = 30  # Anzahl der Tage
days = np.arange(1, n + 1)

# Besucher, Bestellungen, durchschnittlicher Bon
visitors     = np.random.randint(200, 800, size=n)
orders       = (visitors * np.random.uniform(0.05, 0.15, size=n)).astype(int)
avg_check    = np.random.uniform(300, 900, size=n).round(2)
daily_revenue = (orders * avg_check).round(2)

print("=== Daten für den Monat ===")
print(f"{'Tag':>4} {'Besucher':>12} {'Bestellungen':>11} {'Ø Bon':>9} {'Umsatz':>10}")
print("-" * 52)
for i in range(10):  # die ersten 10 Tage
    print(f"{days[i]:>4} {visitors[i]:>12} {orders[i]:>11} {avg_check[i]:>9.0f} {daily_revenue[i]:>10.0f}")
print("... (noch 20 Zeilen) ...")


=== Daten für den Monat ===
 Tag     Besucher Bestellungen     Ø Bon     Umsatz
----------------------------------------------------
   1          302          27       805      21745
   2          635          34       570      19375
   3          470          69       537      37059
   4          306          22       856      18832
   5          271          16       736      11782
   6          220          24       496      11902
   7          321          28       642      17984
   8          666          98       612      60025
   9          414          40       877      35068
  10          530          72       807      58084
... (noch 20 Zeilen) ...


### 🎯 Abschlussaufgabe

Führe eine vollständige Analyse der Shop-Daten durch:

**1. Allgemeine Statistik:**
- Gesamtumsatz für den Monat
- Durchschnittlicher Tagesumsatz
- Bester und schlechtester Tag

**2. Konversion:**
- Berechne die Konversion pro Tag: `orders / visitors * 100`
- Wie hoch ist die durchschnittliche Konversion?
- An wie vielen Tagen lag die Konversion über 10%?

**3. Segmentierung:**
- Finde „starke“ Tage (Umsatz > Durchschnitt)
- Finde „schwache“ Tage (Umsatz < 70% des Durchschnitts)
- Vergleiche den durchschnittlichen Bon an starken und schwachen Tagen

**4. Wochenanalyse:**
- Reshape den Umsatz in das Format (4 Wochen × ... Tage)
- Finde die beste Woche nach Umsatzsumme


In [45]:
# Deine Analyse hier:

# 1. Allgemeine Statistik
print("Gesamtumsatz für den Monat: ", daily_revenue.sum())

print("Durchschnittlicher Tagesumsatz", daily_revenue.mean().round())
print(np.argmax(daily_revenue))
# Bester und schlechtester Tag
best_day = days[np.argmax(daily_revenue)]
print(f"Bester Tag: {best_day}, schlechtester Tag: {days[np.argmin(daily_revenue)]}")

# 2. Konversion

# Berechne die Konversion pro Tag: orders / visitors * 100
conversion = orders / visitors * 100
print(conversion.round(1))

# Wie hoch ist die durchschnittliche Konversion?
print(f"Konversion: {conversion.mean().round(2)}")
# An wie vielen Tagen lag die Konversion über 10%?
print("Konversion > 10% ->", np.sum(conversion > 10))

# 3. Segmentierung
avg_rev = daily_revenue.mean()
# Finde „starke“ Tage (Umsatz > Durchschnitt)
strong_days = daily_revenue > avg_rev
print("„starke“ Tage: ", days[strong_days])
# Finde „schwache“ Tage (Umsatz < 70% des Durchschnitts)
weak_days = daily_revenue <  avg_rev * 0.7
print("„schwache“ Tage: ", days[weak_days])
# Vergleiche den durchschnittlichen Bon an starken und schwachen Tagen
print(f"durchschnittlicher Bon an starken Tagen: {avg_check[strong_days].mean().round()}\n")
print(f"durchschnittlicher Bon an schwachen Tagen: {avg_check[weak_days].mean().round()}\n")









Gesamtumsatz für den Monat:  815310.61
Durchschnittlicher Tagesumsatz 27177.0
7
Bester Tag: 8, schlechtester Tag: 23
[ 8.9  5.4 14.7  7.2  5.9 10.9  8.7 14.7  9.7 13.6 11.7  9.4  5.1 14.4
 10.6  8.7  5.2  7.2  7.3 11.8 11.  13.2  6.7  8.8  6.6 12.2  9.1  7.
 10.5  5. ]
Konversion: 9.37
Konversion > 10% -> 12
„starke“ Tage:  [ 3  8  9 10 11 14 20 22 27 28 29]
„schwache“ Tage:  [ 4  5  6  7 12 13 17 19 23 30]
durchschnittlicher Bon an starken Tagen: 700.0

durchschnittlicher Bon an schwachen Tagen: 595.0



In [46]:
# 4. Wochenanalyse
# Reshape den Umsatz in das Format (4 Wochen × ... Tage)
# Finde die beste Woche nach Umsatzsumme
weekly = daily_revenue[:28].reshape(4,-1)
sum_weekly = weekly.sum(axis=1)
np.argmax(sum_weekly)
print(f"beste Woche nach Umsatzsumme - {np.argmax(sum_weekly)}")


beste Woche nach Umsatzsumme - 1


In [47]:
# 💡 Tipp zum Abschlussprojekt:
hint = """
# 1. Allgemeine Statistik
print("Gesamtumsatz:      ", daily_revenue.sum().round())
print("Durchschnitt/Tag:  ", daily_revenue.mean().round())
best_day  = days[np.argmax(daily_revenue)]
worst_day = days[np.argmin(daily_revenue)]
print(f"Bester Tag: {best_day}, schlechtester: {worst_day}")

# 2. Konversion
conversion = orders / visitors * 100
print("Durchschnittliche Konversion:", conversion.mean().round(2), "%")
print("Tage mit Konv. > 10%:", np.sum(conversion > 10))

# 3. Segmentierung
avg_rev = daily_revenue.mean()
strong  = daily_revenue > avg_rev
weak    = daily_revenue < avg_rev * 0.7
print("Ø Bon an starken Tagen:", avg_check[strong].mean().round())
print("Ø Bon an schwachen Tagen:", avg_check[weak].mean().round())

# 4. Wochen (30 Tage = 4 Wochen × 7 + 2 Tage, wir nehmen die ersten 28)
weekly = daily_revenue[:28].reshape(4, 7)
weekly_totals = weekly.sum(axis=1)
best_week = np.argmax(weekly_totals) + 1
print("Umsatz pro Woche:", weekly_totals.round())
print(f"Beste Woche: #{best_week}")
"""
print(hint)



# 1. Allgemeine Statistik
print("Gesamtumsatz:      ", daily_revenue.sum().round())
print("Durchschnitt/Tag:  ", daily_revenue.mean().round())
best_day  = days[np.argmax(daily_revenue)]
worst_day = days[np.argmin(daily_revenue)]
print(f"Bester Tag: {best_day}, schlechtester: {worst_day}")

# 2. Konversion
conversion = orders / visitors * 100
print("Durchschnittliche Konversion:", conversion.mean().round(2), "%")
print("Tage mit Konv. > 10%:", np.sum(conversion > 10))

# 3. Segmentierung
avg_rev = daily_revenue.mean()
strong  = daily_revenue > avg_rev
weak    = daily_revenue < avg_rev * 0.7
print("Ø Bon an starken Tagen:", avg_check[strong].mean().round())
print("Ø Bon an schwachen Tagen:", avg_check[weak].mean().round())

# 4. Wochen (30 Tage = 4 Wochen × 7 + 2 Tage, wir nehmen die ersten 28)
weekly = daily_revenue[:28].reshape(4, 7)
weekly_totals = weekly.sum(axis=1)
best_week = np.argmax(weekly_totals) + 1
print("Umsatz pro Woche:", weekly_totals.round())
print(f"Beste Woche: #{best

---
## 📋 Spickzettel — Die wichtigsten NumPy-Funktionen

| Funktion | Beschreibung | Beispiel |
|---|---|---|
| `np.array()` | Array erstellen | `np.array([1,2,3])` |
| `np.zeros(shape)` | Array aus Nullen | `np.zeros((3,4))` |
| `np.ones(shape)` | Array aus Einsen | `np.ones((2,5))` |
| `np.arange(start, stop, step)` | Bereich | `np.arange(0,10,2)` |
| `np.linspace(start, stop, n)` | Gleichmäßige Teilung | `np.linspace(0,1,5)` |
| `.shape` | Form des Arrays | `arr.shape` → `(3,4)` |
| `.dtype` | Datentyp | `arr.dtype` → `int64` |
| `.reshape()` | Form ändern | `arr.reshape(2,6)` |
| `.flatten()` | In 1D umwandeln | `arr.flatten()` |
| `.sum()` / `.mean()` | Summe / Mittelwert | `arr.sum(axis=0)` |
| `.min()` / `.max()` | Min / Max | `arr.max()` |
| `.std()` | Standardabweichung | `arr.std()` |
| `np.sort()` | Sortieren | `np.sort(arr)` |
| `np.argmin()` / `np.argmax()` | Index von Min/Max | `np.argmax(arr)` |
| `np.where(cond, a, b)` | Bedingte Zuweisung | `np.where(arr>0, 1, -1)` |
| Boolesche Maske | Filterung | `arr[arr > 5]` |

---

## Wie geht es weiter?

- **pandas** — Tabellendaten, DataFrame
- **matplotlib** — Datenvisualisierung
- **scikit-learn** — maschinelles Lernen (verwendet NumPy im Hintergrund)

Nützliche Ressourcen:
- [Offizielle NumPy-Dokumentation](https://numpy.org/doc/)
- [NumPy Quickstart](https://numpy.org/doc/stable/user/quickstart.html)
