<a href="https://colab.research.google.com/github/Alister44/DTA_2026_DE/blob/main/Hausafgaben/numpy_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Hausaufgabe — NumPy

**Zum Tutorial:** Pandas + Matplotlib: Datenanalyse von Grund auf

---
### Bearbeitungsregeln
- Bearbeite jede Aufgabe in einer eigenen Zelle
- Verwende keine Schleifen, wo man mit NumPy-Operationen auskommt
- Führe nach der Bearbeitung die Zelle aus und prüfe, ob das Ergebnis richtig aussieht
- Wenn du nicht weiterkommst — kehre zum entsprechenden Kapitel des Tutorials zurück

**Bewertung:** jede Aufgabe — 1 Punkt. Abschlussprojekt — 3 Punkte. Insgesamt: **14 Punkte**

---



## Kapitel 1 — ndarray-Arrays und Attribute

> **Was wir wiederholen:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> Attribute `.shape`, `.ndim`, `.size`, `.dtype`


### ✏️ Aufgabe 1.1

Du hast Daten zu den durchschnittlichen Monatstemperaturen in München für ein Jahr (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Erstelle ein NumPy-Array aus diesen Werten und nenne es `temps`
2. Gib das Array aus
3. Gib aus: Anzahl der Dimensionen (`ndim`), Form (`shape`), Anzahl der Elemente (`size`), Datentyp (`dtype`)
4. Gib die minimale, maximale und durchschnittliche Jahrestemperatur aus (auf 1 Stelle runden)


In [1]:
import numpy as np
# Dein Code:
temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])
print("temps Array:", temps)
print(temps.ndim) #Anzahl der Dimensionen (ndim)
print(temps.shape) # Form (shape)
print(temps.size) #Anzahl der Elemente (size)
print(temps.dtype) #Datentyp (dtype)
print(f"min temp: {temps.min()}, max temp: {temps.max()}, average year: {temps.mean().round(1)}")


temps Array: [-5 -4  2 10 17 21 23 22 16  9  2 -3]
1
(12,)
12
int64
min temp: -5, max temp: 23, average year: 9.2


### ✏️ Aufgabe 1.2

Erstelle eine Tabelle mit geplanten Verkaufszahlen für 3 Manager über 4 Quartale.

1. Erstelle eine Matrix `plan` der Größe **3×4**, gefüllt mit dem Wert `50` (Tsd. €) — verwende `np.full()`
2. Gib die Matrix aus
3. Gib ihre Form und die Gesamtzahl der Elemente aus
4. Erstelle eine zweite Matrix `bonus` der Größe **3×4** aus Nullen — die Manager haben noch keine Boni erhalten
5. Gib die Summe `plan + bonus` aus und stelle sicher, dass sie gleich `plan` ist


In [2]:
# Dein Code:
plan = np.full((3,4),50)
print(plan)
print(plan.shape, plan.size) # Form und Gesamtzahl der Elemente

bonus = np.zeros((3,4))
print(plan+bonus)
if np.array_equal(plan,plan+bonus):
    print("arrays are equal")
else:
    print("arrays are not equal")


[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
(3, 4) 12
[[50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]]
arrays are equal


---
## Kapitel 2 — Indizierung und Slicing

> **Was wir wiederholen:** Indizierung von 1D- und 2D-Arrays, Slicing `[start:stop:step]`,
> Auswahl von Zeilen und Spalten einer Matrix


### ✏️ Aufgabe 2.1

Es gibt ein Array mit den täglichen Verkäufen eines Geschäfts über 2 Wochen (14 Tage):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Führe folgende Auswahlen **ohne Schleifen** aus, nur mit Slicing:
1. Verkäufe der ersten Woche (Tage 1–7)
2. Verkäufe der zweiten Woche (Tage 8–14)
3. Verkäufe am Wochenende: 6., 7., 13., 14. Tag — verwende die Indizierung mit einer Liste `[[5,6,12,13]]`
4. Verkäufe jeden zweiten Tag, beginnend mit dem ersten (ungerade Tage: 1, 3, 5...)
5. Das Array in umgekehrter Reihenfolge


In [3]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Dein Code:
print(f"Verkäufe der ersten Woche (Tage 1–7) {sales[:7]}")
print(f"Verkäufe der zweiten Woche (Tage 8–14) {sales[7:]}")
print(f"Verkäufe am Wochenende: 6., 7., 13., 14. Tag {sales[[5,6,12,13]]}")
print(f"Verkäufe jeden zweiten Tag, beginnend mit dem ersten (ungerade Tage: 1, 3, 5...) {sales[0::2]}")
print(f"Array in umgekehrter Reihenfolge {sales[::-1]}")


Verkäufe der ersten Woche (Tage 1–7) [320 415 290 480 350 620 580]
Verkäufe der zweiten Woche (Tage 8–14) [310 440 305 510 370 650 595]
Verkäufe am Wochenende: 6., 7., 13., 14. Tag [620 580 650 595]
Verkäufe jeden zweiten Tag, beginnend mit dem ersten (ungerade Tage: 1, 3, 5...) [320 290 350 580 440 510 650]
Array in umgekehrter Reihenfolge [595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Aufgabe 2.2

Es gibt eine Notenmatrix von Studenten: **4 Studenten × 5 Fächer**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Olena
    [63, 88, 74, 95, 70],   # Maksym
    [90, 65, 82, 70, 94],   # Anja
    [75, 80, 68, 85, 79],   # Bohdan
])
```

1. Gib alle Noten von Olena aus (erste Zeile)
2. Gib die Noten aller Studenten im 3. Fach aus (dritte Spalte)
3. Gib die Untermatrix aus: Noten von Maksym und Anja in den Fächern 2–4 (Zeilen 1–2, Spalten 1–3)
4. Gib die Note des letzten Studenten im letzten Fach aus


In [4]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Dein Code:
print(f"alle Noten von Olena (erste Zeile) {grades[0,:]}")
print(f"Noten aller Studenten im 3. Fach (dritte Spalte) {grades[:,2]}")
print(f"Noten von Maksym und Anja in den Fächern 2–4 (Zeilen 1–2, Spalten 1–3) {grades[1:3,1:4]}")
print(f"Note des letzten Studenten im letzten Fach {grades[-1][-1]}")


alle Noten von Olena (erste Zeile) [85 72 91 78 88]
Noten aller Studenten im 3. Fach (dritte Spalte) [91 74 82 68]
Noten von Maksym und Anja in den Fächern 2–4 (Zeilen 1–2, Spalten 1–3) [[88 74 95]
 [65 82 70]]
Note des letzten Studenten im letzten Fach 79


---
## Kapitel 3 — Mathematische Operationen und Vektorisierung

> **Was wir wiederholen:** Arithmetik mit Arrays, `np.sqrt()`, `np.round()`,
> Aggregatfunktionen `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`


### ✏️ Aufgabe 3.1

Es gibt ein Array mit Produktpreisen in Dollar. Führe **ohne Schleifen** aus:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Rechne die Preise in Euro um (Kurs: **1 USD = 0.92 EUR**), runde das Ergebnis auf 2 Stellen
2. Berechne 19% MwSt. — multipliziere die Euro-Preise mit 1.19, runde auf 2 Stellen
3. Finde: den minimalen, maximalen und durchschnittlichen Preis mit MwSt.
4. Finde die Summe aller Produkte mit MwSt. — das ist der Gesamtwert des Warenkorbs
5. Gib die Ergebnisse mit Erklärungen aus


In [5]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Dein Code:
prices_eur = (prices_usd * 0.92).round(2)
print(f"Preise in Euro (Kurs: 1 USD = 0.92 EUR) {prices_eur}")

prices_vat = (prices_eur * 1.19).round(2)
print(f"Preise mit 19% MwSt. {prices_vat}")

print(f"minimal {prices_vat.min()}, maximal {prices_vat.max()}, durchschnittlicher Preis {prices_vat.mean().round(2)} mit MwSt.")

print(f"Summe aller Produkte mit MwSt. {prices_vat.sum()}")



Preise in Euro (Kurs: 1 USD = 0.92 EUR) [ 14.71  39.1    7.36 115.    31.05  61.82   9.19]
Preise mit 19% MwSt. [ 17.5   46.53   8.76 136.85  36.95  73.57  10.94]
minimal 8.76, maximal 136.85, durchschnittlicher Preis 47.3 mit MwSt.
Summe aller Produkte mit MwSt. 331.09999999999997


### ✏️ Aufgabe 3.2

Es gibt Daten zur Anzahl der Produkte im Lager und ihren Selbstkosten.
Führe **ohne Schleifen** aus:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Kabel', 'Tastatur', 'Notizbuch', 'Monitor',
             'Maus', 'Stift', 'Kopfhörer']
```

1. Berechne den Gesamtwert jedes Produkts im Lager (`quantity * cost_each`)
2. Finde den Gesamtwert des gesamten Lagers
3. Finde das Produkt mit dem höchsten Gesamtwert — verwende `np.argmax()`
4. Finde das Produkt mit dem niedrigsten Gesamtwert — `np.argmin()`
5. Gib den durchschnittlichen Wert einer Produktart im Lager aus


In [6]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Kabel', 'Tastatur', 'Notizbuch', 'Monitor',
             'Maus', 'Stift', 'Kopfhörer']

# Dein Code:
total_cost = quantity * cost_each
print(f"Gesamtwert jedes Produkts im Lager: ", total_cost)

print(f"Gesamtwert des gesamten Lagers: ", total_cost.sum())
#print(f"Gesamtwert des gesamten Lagers: ", np.dot(quantity,cost_each))

print(f"Produkt mit dem höchsten Gesamtwert: ", names[np.argmax(total_cost)])
print(f"Produkt mit dem niedrigsten Gesamtwert: ", names[np.argmin(total_cost)])

print(f"durchschnittlicher Wert einer Produktart: ", total_cost.mean().round(2))


Gesamtwert jedes Produkts im Lager:  [ 30000  81000  13500 171000  28500  24000  45000]
Gesamtwert des gesamten Lagers:  393000
Produkt mit dem höchsten Gesamtwert:  Monitor
Produkt mit dem niedrigsten Gesamtwert:  Notizbuch
durchschnittlicher Wert einer Produktart:  56142.86


---
## Kapitel 4 — Boolesches Maskieren und Filterung

> **Was wir wiederholen:** boolesche Masken, Filterung `arr[mask]`,
> `np.where()`, `.sum()` zum Zählen von True


### ✏️ Aufgabe 4.1

Es gibt ein Array mit Bearbeitungszeiten von Bestellungen in Minuten (Norm — bis zu 30 Min):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Finde alle Bestellungen, die **rechtzeitig** bearbeitet wurden (≤ 30 Min)
2. Finde alle **verspäteten** Bestellungen (> 30 Min)
3. Berechne die Anzahl der rechtzeitigen und der verspäteten
4. Finde den Prozentsatz der verspäteten Bestellungen (auf 1 Stelle runden)
5. Wie hoch ist die durchschnittliche Verspätung bei den verspäteten Bestellungen?


In [7]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Dein Code:
in_time = delivery_time <= 30
print("rechtzeitig bearbeitete Bestellungen (≤ 30 Min): ",delivery_time[in_time])

not_in_time = delivery_time > 30
print("alle verspäteten Bestellungen (> 30 Min): ",delivery_time[not_in_time])

print(f"Anzahl rechtzeitig {in_time.sum()} und verspätet {not_in_time.sum()}")
print(f"Prozentsatz der verspäteten Bestellungen {not_in_time.sum()/len(delivery_time) * 100:.1f}%")
print(f"durchschnittliche Verspätung bei verspäteten Bestellungen: {(delivery_time[not_in_time] - 30).mean()}")


rechtzeitig bearbeitete Bestellungen (≤ 30 Min):  [22 28 19 27 24 26 18 29 23 20]
alle verspäteten Bestellungen (> 30 Min):  [35 41 55 33 48 31 52 38 44 36]
Anzahl rechtzeitig 10 und verspätet 10
Prozentsatz der verspäteten Bestellungen 50.0%
durchschnittliche Verspätung bei verspäteten Bestellungen: 11.3


### ✏️ Aufgabe 4.2

Es gibt ein Array mit täglichen Verkäufen für einen Monat. Verwende `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Finde Tage mit Verkäufen **über dem Durchschnitt** für den Monat
2. Berechne, wie viele solcher Tage es gibt
3. Erstelle mit `np.where()` ein Array `status`:
   - `'Guter Tag'` — wenn die Verkäufe über dem Durchschnitt liegen
   - `'Normaler Tag'` — wenn darunter oder gleich
4. Gib die ersten 10 Tage aus: Verkäufe und ihr Status nebeneinander


In [8]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Dein Code:
print(f"Tage mit Verkäufen über dem Durchschnitt: {daily[daily > daily.mean()]}")
print(f"solcher Tage: {(daily > daily.mean()).sum()}")
status = np.where(daily > daily.mean(),"Guter Tag","Normaler Tag")
print(status)
for sale, st in zip(daily[:10], status[:10]):
    print(f"{sale}  —  {st}")


Tage mit Verkäufen über dem Durchschnitt: [535 800 714 566 558 472 763 761 869 443 591 513 485 559]
solcher Tage: 14
['Normaler Tag' 'Guter Tag' 'Normaler Tag' 'Normaler Tag' 'Normaler Tag'
 'Guter Tag' 'Normaler Tag' 'Guter Tag' 'Normaler Tag' 'Guter Tag'
 'Normaler Tag' 'Normaler Tag' 'Guter Tag' 'Normaler Tag' 'Guter Tag'
 'Normaler Tag' 'Guter Tag' 'Normaler Tag' 'Guter Tag' 'Normaler Tag'
 'Guter Tag' 'Guter Tag' 'Guter Tag' 'Guter Tag' 'Guter Tag'
 'Normaler Tag' 'Normaler Tag' 'Normaler Tag' 'Guter Tag' 'Normaler Tag']
202  —  Normaler Tag
535  —  Guter Tag
370  —  Normaler Tag
206  —  Normaler Tag
171  —  Normaler Tag
800  —  Guter Tag
120  —  Normaler Tag
714  —  Guter Tag
221  —  Normaler Tag
566  —  Guter Tag


---
## Kapitel 5 — reshape und Sortieren

> **Was wir wiederholen:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`


### ✏️ Aufgabe 5.1

Es gibt ein 1D-Array mit 24 Verkaufswerten (nach Stunden über den Tag):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Wandle das Array in eine Matrix **6×4** um (6 Blöcke à 4 Stunden) und gib sie aus
2. Finde die Summe der Verkäufe in jedem 4-Stunden-Block (pro Zeile)
3. Sortiere das ursprüngliche 1D-Array **aufsteigend** und gib es aus
4. Finde die **Indizes** der Stunden, sortiert nach aufsteigenden Verkäufen — `np.argsort()`
5. Gib die Top-3 produktivsten Stunden aus (ihre Nummern, gezählt ab 0)


In [9]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Dein Code:
matrx = hourly.reshape(6,4)
print(matrx)
print(f"Summe der Verkäufe in jedem 4-Stunden-Block {matrx.sum(axis=1)}")
print(f"1D-Array aufsteigend sortiert {np.sort(hourly)}" )
print(f"Indizes der Stunden, sortiert nach aufsteigenden Verkäufen {np.argsort(hourly)}" )
print(f"Top-3 produktivsten Stunden (ihre Nummern, gezählt ab 0) {np.argsort(hourly)[-3:][::-1]}" )


[[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]
Summe der Verkäufe in jedem 4-Stunden-Block [ 28  66 235 240 257 112]
1D-Array aufsteigend sortiert [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]
Indizes der Stunden, sortiert nach aufsteigenden Verkäufen [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]
Top-3 produktivsten Stunden (ihre Nummern, gezählt ab 0) [18 12 19]


---
## Kapitel 6 — Erzeugung von Zufallszahlen

> **Was wir wiederholen:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`


### ✏️ Aufgabe 6.1

Simuliere die Ergebnisse einer Marketingumfrage unter 50 Kunden.

1. Setze `np.random.seed(99)`
2. Generiere das Array `ages` — Alter von 50 Kunden: ganze Zahlen von 18 bis 65
3. Generiere das Array `scores` — Zufriedenheitsbewertungen (Normalverteilung, Mittelwert=7, σ=1.5), auf 1 Stelle runden
4. Begrenze `scores` so, dass die Werte zwischen 1 und 10 liegen — `np.clip(arr, 1, 10)`
5. Gib aus:
   - das durchschnittliche Alter der Kunden
   - die durchschnittliche Zufriedenheitsbewertung
   - die Anzahl der Kunden mit einer Bewertung >= 8 („zufrieden")
   - den Prozentsatz der Zufriedenen


In [10]:
# Dein Code:
rng = np.random.default_rng(seed=99)
ages = rng.integers(18, 66, size=50)
scores = rng.normal(loc=7, scale=1.5, size=50).round(1)
# np.clip begrenzt die Werte des Arrays auf einen vorgegebenen Bereich
#  — alles unter dem Minimum wird zum Minimum, alles über dem Maximum wird zum Maximum.
scores_new = np.clip(scores, 1, 10)
print(f"durchschnittliches Alter der Kunden: {ages.mean().round()}")
print(f"durchschnittliche Zufriedenheitsbewertung: {scores_new.mean().round(2)}")
print(f"Anzahl der Kunden mit einer Bewertung >= 8 („zufrieden\"): {(scores_new >= 8).sum()}")
print(f"Prozentsatz der Zufriedenen: {(scores_new >= 8).sum() / len(scores_new) * 100} %")


durchschnittliches Alter der Kunden: 43.0
durchschnittliche Zufriedenheitsbewertung: 7.27
Anzahl der Kunden mit einer Bewertung >= 8 („zufrieden"): 18
Prozentsatz der Zufriedenen: 36.0 %


---
## 🏆 Abschlussprojekt — Analyse der Shop-Daten

> **Wir verwenden alles aus dem Tutorial zusammen**

Du bist Datenanalyst eines kleinen Elektronikgeschäfts.
Du hast ein Array mit Verkäufen über 8 Wochen (56 Tage) erhalten.

Führe eine vollständige Analyse durch und beantworte die Fragen deines Vorgesetzten.


In [11]:
# Daten — ändere diese Zelle nicht
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Am Wochenende verkauft sich besser
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Daten erhalten. Array sales_56 ist bereit für die Analyse.')
print(f'Elemente: {sales_56.size}, Form: {sales_56.shape}')



Daten erhalten. Array sales_56 ist bereit für die Analyse.
Elemente: 56, Form: (56,)


### Frage 1 — Allgemeine Statistik (Kapitel 1, 3)
Gib aus:
- Gesamtumsatz über 56 Tage
- Durchschnittlicher Tagesumsatz (auf 2 Stellen runden)
- Minimaler und maximaler Tagesverkauf
- Standardabweichung (wie stark die Verkäufe „schwanken")


In [12]:
# Dein Code:
print("Gesamtumsatz über 56 Tage",np.sum(sales_56))
print("Durchschnittlicher Tagesumsatz (auf 2 Stellen gerundet)",np.mean(sales_56).round(2))
print(f"Minimaler Tagesverkauf - {np.min(sales_56)} und maximaler Tagesverkauf {np.max(sales_56)}")
print("Standardabweichung (wie stark die Verkäufe „schwanken\")",np.std(sales_56).round(2))


Gesamtumsatz über 56 Tage 31819
Durchschnittlicher Tagesumsatz (auf 2 Stellen gerundet) 568.2
Minimaler Tagesverkauf - 222 und maximaler Tagesverkauf 1072
Standardabweichung (wie stark die Verkäufe „schwanken") 195.52


### Frage 2 — Wochenanalyse (Kapitel 5)
1. Wandle `sales_56` in eine Matrix **8×7** um (8 Wochen à 7 Tage)
2. Finde den Umsatz jeder Woche (Summe pro Zeile)
3. Finde die beste Woche und gib ihre Nummer (gezählt ab 1) und die Summe aus
4. Finde den durchschnittlichen Tagesumsatz für jeden Wochentag (Durchschnitt pro Spalte)
5. Gib aus, welcher Wochentag im Durchschnitt am profitabelsten ist (0=Mo, 6=So)


In [13]:
# Dein Code:
matx8x7 = sales_56.reshape(8,7)
print("Matrix nach Wochen ",matx8x7)
print("Umsatz jeder Woche ", matx8x7.sum(axis=1))
print(f"beste Woche - {np.argmax(matx8x7.sum(axis=1))+1}, ihre Nummer (gezählt ab 1) und Summe {np.max(matx8x7.sum(axis=1))}")
print("durchschnittlicher Tagesumsatz für jeden Wochentag (Durchschnitt pro Spalte) - ", matx8x7.sum(axis=0))
print("Wochentag, der im Durchschnitt am profitabelsten ist (0=Mo, 6=So) ", np.argmax(matx8x7.sum(axis=0)))


Matrix nach Wochen  [[ 706  739  748  646  383  556  777]
 [ 427  274  522  680  708  465  845]
 [ 447  402  551  567  723  404  469]
 [ 254  314  383  754  297  472 1072]
 [ 773  510  769  798  510  824  852]
 [ 336  297  591  637  296  735  408]
 [ 661  447  734  558  339  710  779]
 [ 559  661  229  222  454  872  673]]
Umsatz jeder Woche  [4555 3921 3563 3546 5036 3300 4228 3670]
beste Woche - 5, ihre Nummer (gezählt ab 1) und Summe 5036
durchschnittlicher Tagesumsatz für jeden Wochentag (Durchschnitt pro Spalte) -  [4163 3644 4527 4862 3710 5038 5875]
Wochentag, der im Durchschnitt am profitabelsten ist (0=Mo, 6=So)  6


### Frage 3 — Filterung und Maskierung (Kapitel 4)
1. Finde die Anzahl der **„schwachen" Tage** — Verkäufe unter 400 €
2. Finde die Anzahl der **„starken" Tage** — Verkäufe über 700 €
3. Wie hoch ist der durchschnittliche Umsatz an schwachen und wie hoch an starken Tagen?
4. Erstelle ein Array `labels` mit `np.where()`:
   - `'Schwach'` wenn < 400
   - `'Stark'` wenn > 700
   - `'Normal'` in allen anderen Fällen (Tipp: verschachteltes `np.where`)
5. Gib die ersten 14 Tage aus: Verkäufe und ihre Bezeichnungen


In [14]:
# Dein Code:
print("Anzahl der „schwachen\" Tage — Verkäufe unter 400 €: ", (sales_56 < 400).sum())
print("Anzahl der „starken\" Tage — Verkäufe über 700 €: ", (sales_56 > 700).sum())
print(f"durchschnittlicher Umsatz an schwachen Tagen - {sales_56[sales_56 < 400].mean().round(2)} an starken - {sales_56[sales_56 > 700].mean().round(2)}" )
labels = np.where(sales_56 < 400, "Schwach", np.where(sales_56 > 700, "Stark", "Normal"))
print(f"erste 14 Tage: Verkäufe und ihre Bezeichnungen ")
for sale, label in zip(sales_56[:14], labels[:14]):
    print(f"{sale} - {label}")


Anzahl der „schwachen" Tage — Verkäufe unter 400 €:  12
Anzahl der „starken" Tage — Verkäufe über 700 €:  19
durchschnittlicher Umsatz an schwachen Tagen - 302.0 an starken - 785.16
erste 14 Tage: Verkäufe und ihre Bezeichnungen 
706 - Stark
739 - Stark
748 - Stark
646 - Normal
383 - Schwach
556 - Normal
777 - Stark
427 - Normal
274 - Schwach
522 - Normal
680 - Normal
708 - Stark
465 - Normal
845 - Stark


---
## ✅ Zusammenfassung

| Kapitel | Aufgabe | Punkte | Erledigt |
|--------|----------|-------|----------|
| 1 — ndarray-Arrays | 1.1, 1.2 | 2 | ☐ |
| 2 — Indizierung und Slicing | 2.1, 2.2 | 2 | ☐ |
| 3 — Mathematische Operationen | 3.1, 3.2 | 2 | ☐ |
| 4 — Boolesches Maskieren | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape und Sortieren | 5.1 | 1 | ☐ |
| 6 — Erzeugung von Zufallszahlen | 6.1 | 1 | ☐ |
| 🏆 Abschlussprojekt | Fragen 1–3 | 3 | ☐ |
| **Gesamt** | | **13** | |

